### ISSUE TITLE
Issue with Version 3.8.3 (29802)

### ISSUE THREAD

**Issue by uxmatt** [redgell/Save-with-Frame#4]
I can't seem to see the save file location when I click the plug-in from the menu.
Steps I followed:
1. Open a new Sketch file
2. Create a new artboard sized for iPhone 6 @1x
3. Selected artboard I want to export that are @1x
4. Click Plugins > Save with Frame > Export iPhone 6 Assets
5. Select the color iPhone you want to frame your artboard
6. **Select where you want to save these images** -- I DON'T SEE THIS.

Is there something that I missed or this is known issue?

Thanks
Matt

**Comment by redgell** [comment]
When you run the plugin it should prompt you for a save path after you
select the type of iPhone you want.

[image: Inline image 1]

On Sun, Jun 19, 2016 at 4:07 PM, uxmatt notifications@github.com wrote:

> I can't seem to see the save file location when I click the plug-in from
> the menu.
> Steps I followed:
> 1. Open a new Sketch file
> 2. Create a new artboard sized for iPhone 6 @1x https://github.com/1x
> 3. Selected artboard I want to export that are @1x
>    https://github.com/1x
> 4. Click Plugins > Save with Frame > Export iPhone 6 Assets
> 5. Select the color iPhone you want to frame your artboard
> 6. _Select where you want to save these images_ -- I DON'T SEE THIS.
> 
> Is there something that I missed or this is known issue?
> 
> Thanks
> Matt
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/redgell/Save-with-Frame/issues/4, or mute the thread
> https://github.com/notifications/unsubscribe/APFon527Ttlq_kyEOx4NXnsi-IZtecyuks5qNa-HgaJpZM4I5QKk
> .

## 

---

Rob Edgell
Director - Connected Software Strategy

Fossil Group
901 S. Central Expwy.
Richardson
TX
75080
United States
www.fossilgroup.com

t: 469-730-7534
m: 214-532-8974
e: redgell@fossil.com

**Comment by uxmatt** [comment]
Yes, I understand that from your imstructions and what I'm saying is though that is not the case. Are u using the latest version, is it working in yours?

On Sun, Jun 19, 2016 at 5:17 PM -0700, "redgell" <notifications@github.com<mailto:notifications@github.com>> wrote:

When you run the plugin it should prompt you for a save path after you
select the type of iPhone you want.

[image: Inline image 1]

On Sun, Jun 19, 2016 at 4:07 PM, uxmatt notifications@github.com wrote:

> I can't seem to see the save file location when I click the plug-in from
> the menu.
> Steps I followed:
> 1. Open a new Sketch file
> 2. Create a new artboard sized for iPhone 6 @1x https://github.com/1x
> 3. Selected artboard I want to export that are @1x
>    https://github.com/1x
> 4. Click Plugins > Save with Frame > Export iPhone 6 Assets
> 5. Select the color iPhone you want to frame your artboard
> 6. _Select where you want to save these images_ -- I DON'T SEE THIS.
> 
> Is there something that I missed or this is known issue?
> 
> Thanks
> Matt
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/redgell/Save-with-Frame/issues/4, or mute the thread
> https://github.com/notifications/unsubscribe/APFon527Ttlq_kyEOx4NXnsi-IZtecyuks5qNa-HgaJpZM4I5QKk
> .

## 

---

Rob Edgell
Director - Connected Software Strategy

Fossil Group
901 S. Central Expwy.
Richardson
TX
75080
United States
www.fossilgroup.com

t: 469-730-7534
m: 214-532-8974
e: redgell@fossil.com

##

**Comment by pmerrity** [comment]
It's working perfectly fine for me. Are you using the latest version of this plugin and/or have you tried reinstalling it? Just download and double click the file. Confirm when it prompts you to overwrite the current one.

**Comment by uxmatt** [comment]
After restart the computer, it started to work now. That was interesting. Thanks anyway!
Just a suggestion, when I try to save - the button was saying "open" you might want to fix with "save". Attached.
