### ISSUE TITLE
Stopped working on sketch version 40

### ISSUE THREAD

**Issue by Senthil27** [redgell/Save-with-Frame#7]
Hi there,

Love this plug-in, use it all the time. Unfortunately, it stopped working once I updated my sketch to version 40. Tried with previous version of sketch, works like a charm. Any scope to fix this please :)?

**Comment by equinusocio** [comment]
And please add iPhone 7/plus and other devices @redgell

**Comment by MYFW93** [comment]
Excellent work man!
waiting for 40.X update :)

**Comment by andrewnenakhov** [comment]
Not working on 40.3, confirm.

**Comment by mwcrowley** [comment]
Confirm that it no longer works on 40.3

**Comment by nissana** [comment]
Can't wait for the update as well. 
Thank you for your great work–it helps us save a lot of time!!

**Comment by MYFW93** [comment]
40.x fixed by @thewinger here :)

-Sketch 40 compatibility.
-Add iPhone 7 device.

https://github.com/thewinger/Save-with-Frame/

**Comment by mwcrowley** [comment]
Thanks a lot @thewinger!

**Comment by redgell** [comment]
Thanks @thewinger .  I've merged your pull request into the main project.

**Comment by alexcamlo** [comment]
Welcome everyone!

**Comment by Senthil27** [comment]
Thanks a lot!
